name: visitor
description: 朋悦比邻
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.1+22

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.5
  dio: ^2.1.0
  crypto: ^2.1.3
  package_info: ^0.4.0+13
  gesture_password: ^0.0.6
  fluttertoast: ^3.1.0
  flutter_swiper: ^1.1.6
  qr_flutter: ^3.1.0
  url_launcher: ^5.4.2
  flutter_webview_plugin: ^0.3.10
  flutter_datetime_picker: ^1.3.1
  flutter_cupertino_date_picker: ^1.0.3
  sqflite: ^1.2.0
  web_socket_channel: ^1.1.0
  flutter_local_notifications: ^0.9.0+1
  path_provider: ^1.5.1
  provider: ^3.0.0+1
#  contacts_service: ^0.2.9
  intl: ^0.16.0
  audioplayers: ^0.13.2
  badges: ^1.1.0
  date_range_picker: ^1.0.5
  lpinyin: ^1.0.7
  flutter_exif_rotation: ^0.2.4
  flutter_des: ^1.1.0
  table_calendar: ^2.1.0
  pin_input_text_field: ^3.0.1
  extended_image: ^0.6.8
  image_picker: ^0.6.2+3
  event_bus: ^1.1.0
  flutter_slidable: ^0.5.4
  getuiflut: ^0.1.7
  cached_network_image: ^2.0.0-rc
  flutter_easyrefresh: ^2.1.0
  flutter_custom_dialog: ^1.0.15
  flutter_screenutil: ^0.7.0
  flutter_svg: ^0.15.00
  amap_location: ^0.2.0
  permission_handler: ^4.4.0+hotfix.2
  flutter_cache_manager: ^1.1.3
  tobias: ^1.6.0+1
  image_crop: ^0.3.2
  alphabet_list_scroll_view: ^1.0.6

  city_pickers:
    git:  https://github.com/hanxu317317/city_pickers.git
#  permission_handler:
#    path: plugin/flutter_permission_handler
  flutter_arcface:
    path: plugin/flutter_arcface
  contacts_service:
    path: plugin/flutter_contacts-master
#  tobias:
#    git:  https://github.com/OpenFlutter/tobias.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/
    - assets/images/message_chat_talking.png
    - assets/images/message_chat_option_delete.png
    - assets/images/Chat_Friend_Search.png
    - assets/images/Chat_Friend_Add.png
    - assets/images/chat_new.png
    - assets/images/chat_friends.png
    - assets/images/book_empty_background.png
    - assets/images/book_add_search.png
    - assets/images/book_add_contacts.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
